using System;
using System.Collections.Generic;
using System.Text;

namespace RabbitFlow.Diagnostics
{

    /// <summary>
    /// Standard header names injected by the publisher and extracted by the consumer.
    /// These are stored as AMQP message headers (string keys, object values).
    /// </summary>
    public static class MessageHeaders
    {
        /// <summary>
        /// Links this message to a broader workflow or request.
        /// If the publisher doesn't provide one, a new GUID is generated.
        /// Header key: x-correlation-id
        /// </summary>
        public const string CorrelationId = "x-correlation-id";

        /// <summary>
        /// Unique identifier for this specific message instance.
        /// Generated by the publisher at publish time.
        /// Header key: x-message-id
        /// </summary>
        public const string MessageId = "x-message-id";

        /// <summary>
        /// UTC timestamp (ISO 8601) of when the message was published.
        /// Header key: x-published-at
        /// </summary>
        public const string PublishedAt = "x-published-at";

        /// <summary>
        /// The <see cref="Configuration.RabbitProducerOptions.ServiceKey"/> of the producer.
        /// Header key: x-publisher-name
        /// </summary>
        public const string PublisherName = "x-publisher-name";

        /// <summary>
        /// The full type name of the event (e.g. "MyApp.Events.OrderCreatedEvent").
        /// Header key: x-event-type
        /// </summary>
        public const string EventType = "x-event-type";

        /// <summary>
        /// The event schema version number.
        /// Header key: x-event-version
        /// </summary>
        public const string EventVersion = "x-event-version";

        /// <summary>
        /// The consumer key that processed (or failed to process) this message.
        /// Set by the consumer, not the publisher.
        /// Header key: x-consumer-key
        /// </summary>
        public const string ConsumerKey = "x-consumer-key";
    }
}
