using System;
using System.Collections.Generic;
using System.Text;

namespace RabbitFlow.Abstractions
{

    /// <summary>
    /// Metadata extracted from RabbitMQ message headers and delivery properties.
    /// Passed to <see cref="IRabbitHandler{T}.HandleAsync"/> alongside the event payload.
    /// Immutable — create a new instance to modify values.
    /// </summary>
    public sealed class MessageContext
    {
        /// <summary>
        /// Correlation ID that links this message to the original request or workflow.
        /// Automatically generated by the publisher if not provided by the caller.
        /// Propagates across service boundaries.
        /// </summary>
        public string? CorrelationId { get; init; }

        /// <summary>
        /// Unique identifier for this specific message.
        /// Generated by the publisher at publish time.
        /// </summary>
        public string? MessageId { get; init; }

        /// <summary>
        /// UTC timestamp of when the publisher sent this message.
        /// </summary>
        public DateTime? PublishedAt { get; init; }

        /// <summary>
        /// The <see cref="Configuration.RabbitProducerOptions.ServiceKey"/> of the producer
        /// that originally published this message.
        /// </summary>
        public string? PublisherName { get; init; }

        /// <summary>
        /// How many times this message has been delivered to a handler (including the current attempt).
        /// First delivery = 1. After one retry = 2. After two retries = 3.
        /// Extracted from the x-death header.
        /// </summary>
        public int RetryCount { get; init; }

        /// <summary>
        /// The consumer tag assigned by RabbitMQ for this consumer instance.
        /// </summary>
        public string? ConsumerTag { get; init; }

        /// <summary>
        /// The routing key that was used to deliver this message.
        /// For topic exchanges, this may differ from the binding key.
        /// </summary>
        public string RoutingKey { get; init; } = string.Empty;

        /// <summary>
        /// The exchange the message was published to.
        /// </summary>
        public string Exchange { get; init; } = string.Empty;

        /// <summary>
        /// AMQP delivery tag. Unique per channel, used for ACK/NACK operations.
        /// Exposed for advanced scenarios where the handler needs to manage acknowledgment manually.
        /// </summary>
        public ulong DeliveryTag { get; init; }

        /// <summary>
        /// Whether this message is a redelivery (previously NACKed with requeue).
        /// </summary>
        public bool Redelivered { get; init; }

        /// <summary>
        /// All custom headers from the message properties.
        /// Does not include internal headers (x-death, x-correlation-id, etc.)
        /// unless they were explicitly set by the publisher.
        /// </summary>
        public IReadOnlyDictionary<string, string> Headers { get; init; } = new Dictionary<string, string>();
    }
}
